/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    blog_posts: BlogPost;
    news_events: NewsEvent;
    open_positions: OpenPosition;
    impact_stories: ImpactStory;
    media_coverage: MediaCoverage;
    outreach_activities: OutreachActivity;
    publications: Publication;
    projects: Project;
    research_themes: ResearchTheme;
    study_sites: StudySite;
    people: Person;
    collaborators: Collaborator;
    media: Media;
    inquiries: Inquiry;
    applicant_files: ApplicantFile;
    users: User;
    audit_log: AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    blog_posts: BlogPostsSelect<false> | BlogPostsSelect<true>;
    news_events: NewsEventsSelect<false> | NewsEventsSelect<true>;
    open_positions: OpenPositionsSelect<false> | OpenPositionsSelect<true>;
    impact_stories: ImpactStoriesSelect<false> | ImpactStoriesSelect<true>;
    media_coverage: MediaCoverageSelect<false> | MediaCoverageSelect<true>;
    outreach_activities: OutreachActivitiesSelect<false> | OutreachActivitiesSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    research_themes: ResearchThemesSelect<false> | ResearchThemesSelect<true>;
    study_sites: StudySitesSelect<false> | StudySitesSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    collaborators: CollaboratorsSelect<false> | CollaboratorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    applicant_files: ApplicantFilesSelect<false> | ApplicantFilesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    audit_log: AuditLogSelect<false> | AuditLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    about: About;
    legal_pages: LegalPage;
    outreach_page: OutreachPage;
    partnerships_page: PartnershipsPage;
    navigation: Navigation;
    page_seo: PageSeo;
    site_settings: SiteSetting;
  };
  globalsSelect: {
    about: AboutSelect<false> | AboutSelect<true>;
    legal_pages: LegalPagesSelect<false> | LegalPagesSelect<true>;
    outreach_page: OutreachPageSelect<false> | OutreachPageSelect<true>;
    partnerships_page: PartnershipsPageSelect<false> | PartnershipsPageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    page_seo: PageSeoSelect<false> | PageSeoSelect<true>;
    site_settings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug?: string | null;
  status: 'draft' | 'review' | 'published';
  /**
   * Auto-set on first publish.
   */
  publishedAt?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  author: number | Person;
  coverImage?: (number | null) | Media;
  /**
   * Auto-computed from body word count.
   */
  readingTimeMinutes?: number | null;
  seoMeta?: {
    /**
     * Defaults to post title if empty.
     */
    title?: string | null;
    /**
     * 120–160 characters recommended.
     */
    description?: string | null;
  };
  /**
   * Auto-publish at this time via the scheduled-publish cron.
   */
  scheduledPublishAt?: string | null;
  createdBy?: (number | null) | User;
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  slug?: string | null;
  role: 'pi' | 'postdoc' | 'phd' | 'ms' | 'staff' | 'alumni';
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: (number | null) | Media;
  email?: string | null;
  /**
   * ORCID identifier, e.g. 0000-0002-1825-0097
   */
  orcid?: string | null;
  googleScholar?: string | null;
  linkedin?: string | null;
  researchgate?: string | null;
  scopus?: string | null;
  /**
   * e.g. Professor, Associate Professor, Dr.
   */
  academicTitle?: string | null;
  institution?: string | null;
  interests?:
    | {
        interest: string;
        id?: string | null;
      }[]
    | null;
  education?:
    | {
        degree: string;
        institution: string;
        country?: string | null;
        startYear?: string | null;
        endYear?: string | null;
        id?: string | null;
      }[]
    | null;
  experience?:
    | {
        role: string;
        institution: string;
        country?: string | null;
        startYear?: string | null;
        endYear?: string | null;
        id?: string | null;
      }[]
    | null;
  grants?:
    | {
        title: string;
        funder?: string | null;
        year?: string | null;
        id?: string | null;
      }[]
    | null;
  joinedDate?: string | null;
  /**
   * Set this to mark the person as alumni on the public site.
   */
  leftDate?: string | null;
  displayOrder?: number | null;
  /**
   * Uncheck to soft-hide from the public site.
   */
  is_active?: boolean | null;
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines. Auto-filled from filename if left blank — please update it with a meaningful description.
   */
  alt: string;
  caption?: string | null;
  /**
   * Original URL where this image was obtained.
   */
  sourceUrl?: string | null;
  /**
   * Attribution for the creator.
   */
  sourceAuthor?: string | null;
  /**
   * License for this image, e.g. CC BY 4.0 or Unsplash License.
   */
  sourceLicense?: string | null;
  isDemo?: boolean | null;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'super_admin' | 'editor' | 'contributor';
  totpSecret?: string | null;
  /**
   * Two-factor authentication status
   */
  totpEnabled?: boolean | null;
  backupCodes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  totpFailedAttempts?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_events".
 */
export interface NewsEvent {
  id: number;
  title: string;
  slug?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'draft' | 'review' | 'published';
  publishedAt?: string | null;
  category: 'award' | 'grant' | 'talk' | 'conference' | 'press';
  date: string;
  venue?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * Only one news/event can be featured at a time.
   */
  isFeaturedHome?: boolean | null;
  registerUrl?: string | null;
  /**
   * Schedule future publication (requires a cron job — wired in a later step).
   */
  scheduledPublishAt?: string | null;
  createdBy?: (number | null) | User;
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open_positions".
 */
export interface OpenPosition {
  id: number;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * e.g. PhD Fellowship, Postdoc, Research Assistant
   */
  type: string;
  /**
   * Uncheck to hide from the public site.
   */
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact_stories".
 */
export interface ImpactStory {
  id: number;
  title: string;
  slug?: string | null;
  status: 'draft' | 'published';
  /**
   * Auto-set on first publish.
   */
  publishedAt?: string | null;
  cover?: (number | null) | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedProjects?: (number | Project)[] | null;
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug?: string | null;
  status: 'ongoing' | 'completed';
  theme?: (number | null) | ResearchTheme;
  /**
   * Aim for ~150 words.
   */
  summary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  objectives?:
    | {
        objective: string;
        id?: string | null;
      }[]
    | null;
  methods?:
    | {
        method: string;
        id?: string | null;
      }[]
    | null;
  funder?: string | null;
  funderAmount?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  coverImage?: (number | null) | Media;
  team?: (number | Person)[] | null;
  partners?: (number | Collaborator)[] | null;
  /**
   * Only one project can be featured at a time. Checking this will unfeature all others.
   */
  isFeaturedHome?: boolean | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  relatedPublications?: (number | Publication)[] | null;
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research_themes".
 */
export interface ResearchTheme {
  id: number;
  name: string;
  /**
   * Auto-generated from name. Edit only when intentionally changing the URL.
   */
  slug?: string | null;
  /**
   * Aim for 100–150 words.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lucide icon name, e.g. "microscope" or "activity".
   */
  icon?: string | null;
  /**
   * Hex color for this theme's map marker, e.g. #0E6E6E
   */
  color: string;
  /**
   * Illustration displayed in the research theme section.
   */
  themeImage?: (number | null) | Media;
  methods?:
    | {
        method: string;
        id?: string | null;
      }[]
    | null;
  displayOrder?: number | null;
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collaborators".
 */
export interface Collaborator {
  id: number;
  name: string;
  type: 'academic' | 'industry' | 'government';
  country: string;
  logo?: (number | null) | Media;
  website?: string | null;
  displayOrder?: number | null;
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  /**
   * Digital Object Identifier — must be unique.
   */
  doi?: string | null;
  title: string;
  authors: {
    author: string;
    id?: string | null;
  }[];
  /**
   * Link to lab member profiles for those who appear in the authors list.
   */
  authorLinks?: (number | Person)[] | null;
  journal?: string | null;
  year: number;
  type: 'journal_article' | 'conference' | 'preprint' | 'book_chapter';
  themeTags?: (number | ResearchTheme)[] | null;
  pdf?: (number | null) | Media;
  isOpenAccess?: boolean | null;
  citationCount?: number | null;
  abstract?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Raw Crossref API response. Auto-populated.
   */
  crossrefRaw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_coverage".
 */
export interface MediaCoverage {
  id: number;
  outlet: string;
  title: string;
  url: string;
  date: string;
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outreach_activities".
 */
export interface OutreachActivity {
  id: number;
  title: string;
  slug?: string | null;
  /**
   * Date of the outreach activity.
   */
  date: string;
  /**
   * e.g. Peshawar, KP
   */
  location: string;
  /**
   * Brief summary shown on the card.
   */
  shortDescription: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional link to a related research project.
   */
  relatedProject?: (number | null) | Project;
  partnerOrgs?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published';
  /**
   * Auto-set on first publish.
   */
  publishedAt?: string | null;
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "study_sites".
 */
export interface StudySite {
  id: number;
  name: string;
  district: string;
  province: string;
  project: number | Project;
  /**
   * Enter coordinates as [longitude, latitude]. Click on the map below to set the point.
   *
   * @minItems 2
   * @maxItems 2
   */
  location: [number, number];
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact messages and Join the Lab applications. Use the tabs above to filter by type. Opening a message marks it as read automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  formType: 'contact' | 'join' | 'partnership';
  organization?: string | null;
  organizationType?: ('industry' | 'academic' | 'ngo' | 'government' | 'other') | null;
  researchInterest?: string | null;
  name: string;
  email: string;
  message: string;
  positionTitle?: string | null;
  /**
   * Filename submitted by the applicant (always stored, even if upload failed).
   */
  cvFilename?: string | null;
  /**
   * Direct Vercel Blob URL. Click to download the file.
   */
  cvUrl?: string | null;
  /**
   * Filename submitted by the applicant (always stored, even if upload failed).
   */
  sopFilename?: string | null;
  /**
   * Direct Vercel Blob URL. Click to download the file.
   */
  sopUrl?: string | null;
  /**
   * Write your reply here. Save first, then click "Generate Reply Letter" to download the A4 PDF.
   */
  replyText?: string | null;
  /**
   * Auto-set when you open the message. Uncheck to flag as unread again.
   */
  isRead?: boolean | null;
  repliedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicant_files".
 */
export interface ApplicantFile {
  id: number;
  /**
   * Applicant's email address (from the inquiry form)
   */
  submittedBy?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit_log".
 */
export interface AuditLog {
  id: number;
  user: number | User;
  action: 'create' | 'update' | 'delete' | 'publish' | 'login';
  entityType: string;
  entityId?: string | null;
  diff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'blog_posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'news_events';
        value: number | NewsEvent;
      } | null)
    | ({
        relationTo: 'open_positions';
        value: number | OpenPosition;
      } | null)
    | ({
        relationTo: 'impact_stories';
        value: number | ImpactStory;
      } | null)
    | ({
        relationTo: 'media_coverage';
        value: number | MediaCoverage;
      } | null)
    | ({
        relationTo: 'outreach_activities';
        value: number | OutreachActivity;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'research_themes';
        value: number | ResearchTheme;
      } | null)
    | ({
        relationTo: 'study_sites';
        value: number | StudySite;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'collaborators';
        value: number | Collaborator;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'applicant_files';
        value: number | ApplicantFile;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'audit_log';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  body?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  coverImage?: T;
  readingTimeMinutes?: T;
  seoMeta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  scheduledPublishAt?: T;
  createdBy?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_events_select".
 */
export interface NewsEventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  status?: T;
  publishedAt?: T;
  category?: T;
  date?: T;
  venue?: T;
  coverImage?: T;
  isFeaturedHome?: T;
  registerUrl?: T;
  scheduledPublishAt?: T;
  createdBy?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "open_positions_select".
 */
export interface OpenPositionsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  type?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impact_stories_select".
 */
export interface ImpactStoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  cover?: T;
  body?: T;
  relatedProjects?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_coverage_select".
 */
export interface MediaCoverageSelect<T extends boolean = true> {
  outlet?: T;
  title?: T;
  url?: T;
  date?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outreach_activities_select".
 */
export interface OutreachActivitiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  location?: T;
  shortDescription?: T;
  body?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  relatedProject?: T;
  partnerOrgs?:
    | T
    | {
        name?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  doi?: T;
  title?: T;
  authors?:
    | T
    | {
        author?: T;
        id?: T;
      };
  authorLinks?: T;
  journal?: T;
  year?: T;
  type?: T;
  themeTags?: T;
  pdf?: T;
  isOpenAccess?: T;
  citationCount?: T;
  abstract?: T;
  crossrefRaw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  theme?: T;
  summary?: T;
  objectives?:
    | T
    | {
        objective?: T;
        id?: T;
      };
  methods?:
    | T
    | {
        method?: T;
        id?: T;
      };
  funder?: T;
  funderAmount?: T;
  startDate?: T;
  endDate?: T;
  coverImage?: T;
  team?: T;
  partners?: T;
  isFeaturedHome?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  relatedPublications?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research_themes_select".
 */
export interface ResearchThemesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  color?: T;
  themeImage?: T;
  methods?:
    | T
    | {
        method?: T;
        id?: T;
      };
  displayOrder?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "study_sites_select".
 */
export interface StudySitesSelect<T extends boolean = true> {
  name?: T;
  district?: T;
  province?: T;
  project?: T;
  location?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  bio?: T;
  photo?: T;
  email?: T;
  orcid?: T;
  googleScholar?: T;
  linkedin?: T;
  researchgate?: T;
  scopus?: T;
  academicTitle?: T;
  institution?: T;
  interests?:
    | T
    | {
        interest?: T;
        id?: T;
      };
  education?:
    | T
    | {
        degree?: T;
        institution?: T;
        country?: T;
        startYear?: T;
        endYear?: T;
        id?: T;
      };
  experience?:
    | T
    | {
        role?: T;
        institution?: T;
        country?: T;
        startYear?: T;
        endYear?: T;
        id?: T;
      };
  grants?:
    | T
    | {
        title?: T;
        funder?: T;
        year?: T;
        id?: T;
      };
  joinedDate?: T;
  leftDate?: T;
  displayOrder?: T;
  is_active?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collaborators_select".
 */
export interface CollaboratorsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  country?: T;
  logo?: T;
  website?: T;
  displayOrder?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  sourceUrl?: T;
  sourceAuthor?: T;
  sourceLicense?: T;
  isDemo?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  formType?: T;
  organization?: T;
  organizationType?: T;
  researchInterest?: T;
  name?: T;
  email?: T;
  message?: T;
  positionTitle?: T;
  cvFilename?: T;
  cvUrl?: T;
  sopFilename?: T;
  sopUrl?: T;
  replyText?: T;
  isRead?: T;
  repliedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicant_files_select".
 */
export interface ApplicantFilesSelect<T extends boolean = true> {
  submittedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  totpSecret?: T;
  totpEnabled?: T;
  backupCodes?: T;
  totpFailedAttempts?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit_log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  user?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  diff?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Content for /about — mission, director message, KMU affiliation, facilities, testimonials.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  mission?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  directorMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  directorPortrait?: (number | null) | Media;
  kmuAffiliation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  facilities?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  testimonials?:
    | {
        quote: string;
        name: string;
        role: string;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Privacy Policy and Terms of Use — displayed at /privacy and /terms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_pages".
 */
export interface LegalPage {
  id: number;
  privacyPolicyTitle?: string | null;
  privacyPolicy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  termsOfUseTitle?: string | null;
  termsOfUse?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for /outreach — introductory text and section heading.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outreach_page".
 */
export interface OutreachPage {
  id: number;
  /**
   * Introductory paragraph displayed at the top of the Outreach page.
   */
  introText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Heading above the activity list.
   */
  sectionTitle?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for /collaborations (Partnerships page) — hero, why partner with us, offerings, infrastructure, who we work with, example projects, partnership models, and CTA.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerships_page".
 */
export interface PartnershipsPage {
  id: number;
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  heroDescription?: string | null;
  whyPartnerTitle?: string | null;
  whyPartnerSubtitle?: string | null;
  strengths?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  whatWeOfferTitle?: string | null;
  whatWeOfferSubtitle?: string | null;
  offerings?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  infrastructureTitle?: string | null;
  infrastructureTagline?: string | null;
  infrastructureOverview?: string | null;
  infrastructurePillars?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  whoWeWorkWithTitle?: string | null;
  whoWeWorkWithSubtitle?: string | null;
  sectors?:
    | {
        title: string;
        items?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  projectsTitle?: string | null;
  projectsSubtitle?: string | null;
  exampleProjects?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  modelsTitle?: string | null;
  modelsSubtitle?: string | null;
  models?:
    | {
        title: string;
        desc: string;
        id?: string | null;
      }[]
    | null;
  collaboratorsTitle?: string | null;
  collaboratorsSubtitle?: string | null;
  ctaTitle?: string | null;
  ctaDescription?: string | null;
  ctaEmail?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Header navigation links and footer link groups. Changes take effect on the next page view.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Ordered list of links shown in the top nav and mobile menu.
   */
  headerLinks?:
    | {
        label: string;
        /**
         * Use /path for internal pages, https://… for external.
         */
        href: string;
        isExternal?: boolean | null;
        isVisible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Each group appears as a labelled column in the footer.
   */
  footerGroups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              isExternal?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Per-page SEO overrides — title, description, and OG image for each static page. All fields are optional; blank = use global defaults.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page_seo".
 */
export interface PageSeo {
  id: number;
  home?: {
    /**
     * Overrides the default page title. Leave blank to use the hardcoded page title.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Overrides the default OG image for social sharing (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
  };
  about?: {
    /**
     * Overrides the default page title. Leave blank to use the hardcoded page title.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Overrides the default OG image for social sharing (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
  };
  research?: {
    /**
     * Overrides the default page title. Leave blank to use the hardcoded page title.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Overrides the default OG image for social sharing (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
  };
  projects?: {
    /**
     * Overrides the default page title. Leave blank to use the hardcoded page title.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Overrides the default OG image for social sharing (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
  };
  publications?: {
    /**
     * Overrides the default page title. Leave blank to use the hardcoded page title.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Overrides the default OG image for social sharing (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
  };
  collaborations?: {
    /**
     * Overrides the default page title. Leave blank to use the hardcoded page title.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Overrides the default OG image for social sharing (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
  };
  impact?: {
    /**
     * Overrides the default page title. Leave blank to use the hardcoded page title.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Overrides the default OG image for social sharing (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
  };
  news?: {
    /**
     * Overrides the default page title. Leave blank to use the hardcoded page title.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Overrides the default OG image for social sharing (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
  };
  blog?: {
    /**
     * Overrides the default page title. Leave blank to use the hardcoded page title.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Overrides the default OG image for social sharing (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
  };
  join?: {
    /**
     * Overrides the default page title. Leave blank to use the hardcoded page title.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Overrides the default OG image for social sharing (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
  };
  contact?: {
    /**
     * Overrides the default page title. Leave blank to use the hardcoded page title.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Overrides the default OG image for social sharing (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
  };
  outreach?: {
    /**
     * Overrides the default page title. Leave blank to use the hardcoded page title.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Overrides the default OG image for social sharing (1200×630 recommended).
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Global site configuration — lab name, branding, footer, SEO, CTAs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_settings".
 */
export interface SiteSetting {
  id: number;
  labName: string;
  /**
   * Bold statement displayed as the hero H1 (5–8 words).
   */
  tagline?: string | null;
  /**
   * One-line descriptor shown below the headline — e.g. "Institute of Basic Medical Science, KMU Peshawar".
   */
  heroSubline?: string | null;
  /**
   * Second line shown below the subline in teal italic — e.g. "Advancing Microbiome Science for Better Health".
   */
  heroMotto?: string | null;
  logo?: (number | null) | Media;
  /**
   * Upload the white/reversed logo variant. Shown automatically when the site is in dark mode.
   */
  logoDark?: (number | null) | Media;
  footerText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  copyright?: string | null;
  social?: {
    twitter?: string | null;
    linkedin?: string | null;
    researchgate?: string | null;
    github?: string | null;
  };
  contactAddress?: string | null;
  /**
   * e.g. G-XXXXXXXXXX
   */
  analyticsId?: string | null;
  recaptchaSiteKey?: string | null;
  seoDefaults?: {
    /**
     * Appended to every page title, e.g. "| NOG Lab".
     */
    titleSuffix?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * Control the home-page hero background. "Particles" = animated SVG blobs (default). "Video" = looping video. "Image" = static photo.
   */
  heroMedia?: {
    style?: ('particles' | 'video' | 'image') | null;
    video?: (number | null) | Media;
    image?: (number | null) | Media;
  };
  heroCtaPrimary?: {
    label?: string | null;
    href?: string | null;
  };
  heroCtaSecondary?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Key research questions displayed on the home page.
   */
  bigQuestions?:
    | {
        question: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Display labels for each role on the /people page tabs.
   */
  roleLabels?: {
    all?: string | null;
    pi?: string | null;
    postdoc?: string | null;
    phd?: string | null;
    ms?: string | null;
    staff?: string | null;
    alumni?: string | null;
  };
  newsletterEmbedUrl?: string | null;
  brochure?: (number | null) | Media;
  /**
   * Paste the src URL from Google Maps "Embed a map". Shown on /contact with click-to-load.
   */
  googleMapsEmbedUrl?: string | null;
  /**
   * Shown on /join when no active positions exist.
   */
  noOpenPositionsMessage?: string | null;
  /**
   * Displayed on the /contact page.
   */
  contactEmail?: string | null;
  /**
   * Used to compute "Years Active" in the hero stat counters (e.g. 2019).
   */
  foundingYear?: number | null;
  /**
   * Toggle which sections appear on the home page.
   */
  homeSections?: {
    showAboutTeaser?: boolean | null;
    showAboutFull?: boolean | null;
    showFeaturedProject?: boolean | null;
    showProjectsGrid?: boolean | null;
    showMap?: boolean | null;
    showPublications?: boolean | null;
    showTeam?: boolean | null;
    showNews?: boolean | null;
    showPartners?: boolean | null;
  };
  /**
   * Control which tabs appear on the /blog page.
   */
  blogSettings?: {
    showArticles?: boolean | null;
    showNewsEvents?: boolean | null;
  };
  /**
   * Configure the cookie consent banner shown to new visitors.
   */
  cookieConsent?: {
    enabled?: boolean | null;
    /**
     * Leave blank to use the default privacy-first analytics text.
     */
    description?: string | null;
    acceptLabel?: string | null;
    declineLabel?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  mission?: T;
  directorMessage?: T;
  directorPortrait?: T;
  kmuAffiliation?: T;
  facilities?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        name?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  privacyPolicyTitle?: T;
  privacyPolicy?: T;
  termsOfUseTitle?: T;
  termsOfUse?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outreach_page_select".
 */
export interface OutreachPageSelect<T extends boolean = true> {
  introText?: T;
  sectionTitle?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerships_page_select".
 */
export interface PartnershipsPageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroDescription?: T;
  whyPartnerTitle?: T;
  whyPartnerSubtitle?: T;
  strengths?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  whatWeOfferTitle?: T;
  whatWeOfferSubtitle?: T;
  offerings?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  infrastructureTitle?: T;
  infrastructureTagline?: T;
  infrastructureOverview?: T;
  infrastructurePillars?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  whoWeWorkWithTitle?: T;
  whoWeWorkWithSubtitle?: T;
  sectors?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              name?: T;
              id?: T;
            };
        id?: T;
      };
  projectsTitle?: T;
  projectsSubtitle?: T;
  exampleProjects?:
    | T
    | {
        title?: T;
        id?: T;
      };
  modelsTitle?: T;
  modelsSubtitle?: T;
  models?:
    | T
    | {
        title?: T;
        desc?: T;
        id?: T;
      };
  collaboratorsTitle?: T;
  collaboratorsSubtitle?: T;
  ctaTitle?: T;
  ctaDescription?: T;
  ctaEmail?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  headerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        isExternal?: T;
        isVisible?: T;
        id?: T;
      };
  footerGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              isExternal?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page_seo_select".
 */
export interface PageSeoSelect<T extends boolean = true> {
  home?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  about?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  research?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  projects?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  publications?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  collaborations?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  impact?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  news?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  blog?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  join?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  outreach?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  labName?: T;
  tagline?: T;
  heroSubline?: T;
  heroMotto?: T;
  logo?: T;
  logoDark?: T;
  footerText?: T;
  copyright?: T;
  social?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        researchgate?: T;
        github?: T;
      };
  contactAddress?: T;
  analyticsId?: T;
  recaptchaSiteKey?: T;
  seoDefaults?:
    | T
    | {
        titleSuffix?: T;
        ogImage?: T;
      };
  heroMedia?:
    | T
    | {
        style?: T;
        video?: T;
        image?: T;
      };
  heroCtaPrimary?:
    | T
    | {
        label?: T;
        href?: T;
      };
  heroCtaSecondary?:
    | T
    | {
        label?: T;
        href?: T;
      };
  bigQuestions?:
    | T
    | {
        question?: T;
        id?: T;
      };
  roleLabels?:
    | T
    | {
        all?: T;
        pi?: T;
        postdoc?: T;
        phd?: T;
        ms?: T;
        staff?: T;
        alumni?: T;
      };
  newsletterEmbedUrl?: T;
  brochure?: T;
  googleMapsEmbedUrl?: T;
  noOpenPositionsMessage?: T;
  contactEmail?: T;
  foundingYear?: T;
  homeSections?:
    | T
    | {
        showAboutTeaser?: T;
        showAboutFull?: T;
        showFeaturedProject?: T;
        showProjectsGrid?: T;
        showMap?: T;
        showPublications?: T;
        showTeam?: T;
        showNews?: T;
        showPartners?: T;
      };
  blogSettings?:
    | T
    | {
        showArticles?: T;
        showNewsEvents?: T;
      };
  cookieConsent?:
    | T
    | {
        enabled?: T;
        description?: T;
        acceptLabel?: T;
        declineLabel?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}