// This file is auto-generated by `npm run payload generate:importmap`.
// Manually extended: DoiFetchButton added because generate:importmap is blocked
// by a pre-existing ESM issue in the TOTP route (jsonwebtoken named export).
// Re-run `npm run payload generate:importmap` once that is fixed.

import { DoiFetchButton as DoiFetchButton_a8f9b3c2 } from '@/components/admin/DoiFetchButton'

export const importMap = {
  '@/components/admin/DoiFetchButton#DoiFetchButton': DoiFetchButton_a8f9b3c2,
}
